globalConfig:
  secret:
    stringData:
      client: "irodsfuse"
      host: ""
      port: "1247"
      zone: "ucsb"
      user: ""
      password: ""
      retainData: "false"
      enforceProxyAccess: "false"
      mountPathWhitelist: "/ucsb/home"
nodeService:
  irodsPool:
    extraArgs:
      - '--cache_timeout_settings=[{"path":"/","timeout":"-1ns","inherit":false},{"path":"/ucsb","timeout":"-1ns","inherit":false},{"path":"/ucsb/home","timeout":"1h","inherit":false},{"path":"/ucsb/home/public","timeout":"1h","inherit":true}]'
      - --cache_size_max=10737418240
      - --data_root=/irodsfs-pool
      