apiVersion: v1
kind: PersistentVolume
metadata:
  name: irods-test-pv
  labels:
    volumeName: irods-test-pv
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: irods-sc
  csi:
    driver: irods.csi.cyverse.org
    volumeHandle: irods-irodsfuse-vol-id
    volumeAttributes:
      path: "/ucsb/home"
