apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: irods-test-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: irods-sc
  resources:
    requests:
      storage: 5Gi
  selector:
    matchLabels:
      volumeName: irods-test-pv
